[package]
name = "aligned_alloc"
version = "0.1.0"
authors = ["Jonas Schievink <jonas@schievink.net>"]
description = """
Provides cross-platform primitives for aligned memory allocation
"""

[dependencies]
libc = "0.1"
winapi = "0.2"
kernel32-sys = "0.1"
